name: Publish to Maven Central / OSSRH
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Set up Java
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          java-version: 21
          distribution: 'zulu' # openjdk
      - name: Publish package
        run: gradle -Dprofile=release publishToSonatype closeAndReleaseSonatypeStagingRepository
        env:
           ORG_GRADLE_PROJECT_sonatypeUsername : ${{ secrets.OSSRH_USERNAME }}
           ORG_GRADLE_PROJECT_sonatypePassword : ${{ secrets.OSSRH_PASSWORD }}
           ORG_GRADLE_PROJECT_signingKey : ${{ secrets.SIGNING_KEY }}
           ORG_GRADLE_PROJECT_signingPassword : ${{ secrets.SIGNING_SECRET }}
